version: '3'
services:
  game-server:
    image: docker.io/library/my-game-server:1.0 
    ports:
      - "8000:8000"
      - "8484-8490:8484-8490"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      EXTERNAL_IP: ${EXTERNAL_IP}
      # APP_ENVIRONMENT: production

    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
